[project]
name = "entre_fleet"
authors = [{ name = "Entretech", email = "info@entretech.co.mz" }]
description = "Gestao de Frotas - Entretech"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
